// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfEmKOB5Pa1xxAl7GG5SsbqdymVULsNHc',
    appId: '1:588637140407:android:7cdd6850f2222093e6a432',
    messagingSenderId: '588637140407',
    projectId: 'coolcoolcoffee-2a74f',
    databaseURL: 'https://coolcoolcoffee-2a74f-default-rtdb.firebaseio.com',
    storageBucket: 'coolcoolcoffee-2a74f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2rWyb3-EyyIc8LW62plEhVTwTXV095M',
    appId: '1:588637140407:ios:080646f359c30bcce6a432',
    messagingSenderId: '588637140407',
    projectId: 'coolcoolcoffee-2a74f',
    databaseURL: 'https://coolcoolcoffee-2a74f-default-rtdb.firebaseio.com',
    storageBucket: 'coolcoolcoffee-2a74f.appspot.com',
    iosBundleId: 'com.eunhwa.coolcoolcoffeeFrontend',
  );
}
